name: Feed integration automation

on:
  # Added the workflow_dispatch to enable running from UI.
  workflow_dispatch: {}

jobs:
  generate-mismatch-report:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout the repository content
      - name: checkout repo content
        uses: actions/checkout@v3

      # install the python version needed
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # try extracting dependencies from cache
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      # install python packages
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # run the script
      - name: execute the script
        env:
          MMS_URL: http://mall-management-service-prod-api.mall.adeptmind.ai
        run: python actions.py

      # commit the changes
#      - name: commit files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add -A
#          git diff-index --quiet HEAD || (git commit -m "feat: config updates as per SMT changes")

      # push the changes on remote with branch feed_integration_automate
#      - name: push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: feed_integration_automate
#          force: true
      # set a date-time variable to use it in the commit message and pull request title
      - name: set current date and time as env variable
        run: echo "NOW=$(date +'%Y-%m-%d(%H:%M:%S)')" >> $GITHUB_ENV

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: config updates as per SMT changes ${{ env.NOW }}'
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: feed_integration_automate_1
          base: master
          delete-branch: true
          title: 'feat: config updates as per SMT changes'
          body: |
            The changes are done as per the latest SMT details.
          labels: |
            automated pr
            add feeds
            remove feeds
          assignees: deepak-bhardwaj-adeptmind
          reviewers: deepak-bhardwaj-adeptmind
