name: Jellyfish migration

on:
  # Added the workflow_dispatch to enable running from UI.
  workflow_dispatch:
    inputs:
      scrape_urls_to_aggregate_ids_map:
        description: 'Add the scrape urls and their respective aggregate ids'
        required: true
        default: '{"scrape_url_1": "aggregate_ids_1", "scrape_url_2": "aggregate_ids_2"}'

jobs:
  jellyfish-migration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout the repository content
      - name: checkout repo content
        uses: actions/checkout@v3

      # install the python version needed
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install click

      # run the script
      - name: execute the script
        id: execute-the-script
        env:
          MMS_URL: http://mall-management-service-prod-api.mall.adeptmind.ai
        run: |
          PYTHONPATH=. python scripts/cli/main.py migrate-to-jellyfish --url_to_ag_id '${{ github.event.inputs.scrape_urls_to_aggregate_ids_map }}'

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: jellyfish migration'
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: jellyfish_migration
          base: master
          delete-branch: true
          title: 'feat: jellyfish migration'
          body: |
            The changes are done as per the latest SMT details.
            ${{ steps.execute-the-script.outputs.INTEGRATED_FEEDS_LOGS }}
          labels: |
            jellyfish migration
          reviewers: deepak-bhardwaj-adeptmind
          draft: false
